# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chrome Extension CI

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'chrome-extension-dataworks-enhance.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifacts: "chrome-extension-dataworks-enhance.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
